Update to 0.15.0; use ES Module Shims (#275)
* Update changelog for last release

* Update purescript deps for 0.15.2; drop cst dep

* Upgrade to latest pkg set; install entire set

* Get server code to compile

* Use ES Modules Shims for iframe shims

* Add serve:production script

* Add instructions for adding shims to import map

* Doc how to calc integrity hash

* Fix infinite invocation of `main` call

* Update base to production; fail CI if not that

* Update readme instructions

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -72,6 +72,12 @@ jobs:
           npm run build
           npm run test
           npm run build:production
+          if [ "/output/ignored/" != "$(cat public/frame.html | grep '<base' | sed -E 's/ +<base href="([^"]+)">/\1/;')" ]; then
+            echo "client/public/frame.html's 'base' element refers to the wrong path"
+            echo "Run 'npm run base:production' in the 'client' dir, and push the update as a commit"
+            echo "CI will fail until then"
+            exit 1
+          fi
 
       - name: Build client assets
         if: github.event_name == 'release'
