Add PureScript & Package Set version info (#280)
* Clearly indicate PureScript & package set version

* Update RELEASE.md on updating versions via script

* Add CI check for versions

* Add changelog entry

* Ensure CI catches purs version diff

* Update purs version back to 0.15.2

* Ensure CI check catches package set difference

* Update package set version to correct one

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -74,6 +74,18 @@ jobs:
           npm run build:production
           npm run bundle
 
+      - name: Check SharedConfig.purs versions
+        run: |
+          cd client
+          cp src/Try/SharedConfig.purs sharedConfig.out
+          node updateSharedConfigVersions.mjs sharedConfig.out
+          diff src/Try/SharedConfig.purs sharedConfig.out || {
+            echo 'PureScript and/or package set versions in "client/src/Try/SharedConfig.purs"'
+            echo 'do not match the versions extracted from "stack.yaml" and "staging/packages.dhall".'
+            echo 'Please run "cd client && npm run updateConfigVersions". CI will fail until then.'
+            exit 1
+          }
+
       - name: Build client assets
         if: github.event_name == 'release'
         run: |
